### ISSUE TITLE
Could you share the model checkpoint?

### ISSUE THREAD

**Issue by kjappelbaum** [rxn4chemistry/paragraph2actions#4]
Hi 👋🏽 , 

Awesome work. Thanks for sharing the code! 
We are trying to build on top of your work, and for this, we are trying to reproduce your results. 
For this, it would be great if we could also test the model you trained. Could you perhaps also share the checkpoint of the model you used to compute the metrics? 

Cheers,
Kevin

**Comment by avaucher** [comment]
Hi Kevin, 
The model checkpoints are available as part of the following HuggingFace Space: https://huggingface.co/spaces/rxn4chemistry/synthesis-protocol-extraction/tree/main. 

The model from the publication is the ensemble model combining `organic-1.pt`, `organic-2.pt`, and `organic-3.pt`. The sentencepiece model needed for tokenization is also available there. You will also see the code to run them in `app.py`.

This is probably the easiest way to obtain the checkpoints; let me know if you need anything else.
